import math

# screen
WIDTH = 1200
HEIGHT = 800
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60
TILE = 100
FPS_POS = (WIDTH - 35, 5)
PENTA_HEIGHT = 5 * HEIGHT

# colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 100, 0)
BLUE = (100, 100, 200)
DARK_GRAY = (100, 100, 100)
PURPLE = (120, 0, 120)

#player
player_pos = (HALF_WIDTH, HALF_HEIGHT)
player_angle = 0
player_speed = 2

#ray casting 
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 400
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJ_COEFF =  3 * DIST * TILE
SCALE = WIDTH // NUM_RAYS

#map
MINIMAP_SCALE = 5
MINIMAP_RES = (WIDTH // MINIMAP_SCALE, HEIGHT // MINIMAP_SCALE)
MAP_SCALE = 2 * MINIMAP_SCALE
MAP_TILE = TILE // MAP_SCALE
MAP_POS = (0, 0)


#textures
TEXTURE_WIDTH = 420
TEXTURE_HEIGHT = 420
TEXTURE_SCALE = TEXTURE_WIDTH // TILE